#!/usr/bin/env python3
"""UMS V1 - tools/make_dist.py                                        (ST-6)

Builds the single-file versions in dist/.

Customizer sites will not follow an include, so each top-level file is rewritten
with its libraries pasted in where the include stood. The parameter block sits
above that and is untouched, which is what the Customizer reads.

The build is verified rather than assumed: every variant in the matrices is
rendered from both the multi-file and the single-file version and the two
meshes are compared facet for facet.

  python3 tools/make_dist.py            build and verify
  python3 tools/make_dist.py --build    build only
"""
import argparse
import hashlib
import json
import os
import re
import subprocess
import sys

INCLUDE = re.compile(r'^\s*include\s*<([^>]+)>\s*$')
HEADER = """// =====================================================================
//  {name} - single file build
//
//  Generated by tools/make_dist.py from {src} and the files it includes.
//  Do not edit: edit the sources and rebuild. This version exists so the
//  Customizer on a model-sharing site, which will not follow an include,
//  can read the parameters and render the part.
//
//  Sources inlined: {libs}
//  Built from source fingerprint {digest}
// =====================================================================

"""


def inline(path, seen=None):
    seen = seen if seen is not None else []
    out = []
    base = os.path.dirname(path)
    for line in open(path):
        m = INCLUDE.match(line)
        if not m:
            out.append(line)
            continue
        inc = os.path.normpath(os.path.join(base, m.group(1)))
        if inc in seen:
            out.append(f"// (already inlined: {os.path.basename(inc)})\n")
            continue
        seen.append(inc)
        out.append(f"\n// ---- inlined from {os.path.basename(inc)} "
                   f"{'-' * max(0, 48 - len(os.path.basename(inc)))}\n")
        out.extend(inline(inc, seen))
        out.append(f"// ---- end of {os.path.basename(inc)}\n\n")
    return out


def build(src, dest):
    seen = []
    body = inline(src, seen)
    digest = hashlib.sha256(
        b"".join(open(p, "rb").read() for p in [src] + seen)).hexdigest()[:12]
    head = HEADER.format(name=os.path.basename(dest), src=os.path.basename(src),
                         libs=", ".join(os.path.basename(p) for p in seen),
                         digest=digest)
    os.makedirs(os.path.dirname(dest), exist_ok=True)
    with open(dest, "w") as fh:
        fh.write(head)
        fh.writelines(body)
    return seen, digest


def render(scad, params, out):
    cmd = ["openscad", "-o", out]
    for k, v in params.items():
        cmd += ["-D", f'{k}="{v}"' if isinstance(v, str) else f"{k}={json.dumps(v)}"]
    cmd.append(scad)
    subprocess.run(cmd, capture_output=True, text=True, timeout=900)
    return os.path.exists(out)


def mesh_digest(path):
    """Order-independent fingerprint of a mesh: sorted rounded facets."""
    import numpy as np
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    from check_interface import load_stl
    tri = load_stl(path)
    key = np.sort(np.round(tri.reshape(len(tri), 9), 4), axis=1)
    key = key[np.lexsort(key.T[::-1])]
    return hashlib.sha256(key.tobytes()).hexdigest()[:16], len(tri)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--build", action="store_true", help="skip the comparison")
    args = ap.parse_args()

    pairs = [("ums_hook.scad", "dist/ums_hook.scad",
              ["tests/st2_variants.json", "tests/st3_variants.json",
               "tests/st4_variants.json"]),
             ("ums_front_blank.scad", "dist/ums_front_blank.scad", []),
             ("ums_bottle_holder.scad", "dist/ums_bottle_holder.scad",
              ["tests/st7_variants.json"])]

    bad = 0
    for src, dest, matrices in pairs:
        seen, digest = build(src, dest)
        print(f"{dest}: {len(seen)} libraries inlined, "
              f"{os.path.getsize(dest) // 1024} kB, fingerprint {digest}")
        if args.build:
            continue
        cases = {"defaults": {}}
        for m in matrices:
            for name, params in json.load(open(m)).items():
                cases[name] = params
        if not matrices:
            cases.update({"blank": {"mode": "blank"},
                          "pilot": {"fix": "pilot"},
                          "nut_left": {"nut_side": "left"}})
        os.makedirs("out", exist_ok=True)
        for name, params in cases.items():
            p = {k: v for k, v in params.items() if k != "orient"}
            a, b = f"out/dist_a_{name}.stl", f"out/dist_b_{name}.stl"
            if not (render(src, p, a) and render(dest, p, b)):
                print(f"    {name:22s} RENDER FAILED")
                bad += 1
                continue
            da, na = mesh_digest(a)
            db, nb = mesh_digest(b)
            same = da == db
            bad += 0 if same else 1
            print(f"    {name:22s} {na:6d} facets   "
                  f"{'identical' if same else 'DIFFERENT'}")
            os.remove(a)
            os.remove(b)
    print("->", "PASS" if bad == 0 else f"{bad} MISMATCH(ES)")
    return 0 if bad == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
